# Team Member 1 : Dipika Pushpakaran (11810132)
# Team Member 2 : Shrey Nayak (11810033)
# Team Member 3 : Pooja Patil (11810123)

try(require("shinythemes")||install.packages('shinythemes'))
try(require("ggplot2")||install.packages('ggplot2'))
try(require("ggraph")||install.packages('ggraph'))
try(require("corrplot")||install.packages('corrplot'))
try(require("shiny")||install.packages('shiny'))
try(require("udpipe")||install.packages('udpipe'))
try(require("stringr")||install.packages('stringr'))
try(require("wordcloud")||install.packages('wordcloud'))
try(require("dplyr")||install.packages('dplyr'))


library("shinythemes")
library("ggplot2")
library("ggraph")
library("corrplot")
library("shiny")
library("udpipe")
library("stringr")
library("wordcloud")
library("dplyr")
